# Generated by Django 4.0.5 on 2022-06-21 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_forum_delete_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['created', 'title_fio'], 'verbose_name_plural': 'Отзывы посетителей'},
        ),
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/% Y/% m/% d/', verbose_name='Добавьте аватар'),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_fio',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forum',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания отзыва'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='message',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
    ]
