# Generated by Django 4.0.5 on 2022-06-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('name', models.CharField(max_length=100, verbose_name='Название ресторана (одно и то же)')),
            ],
            options={
                'verbose_name_plural': 'Главная страница - тайтлы в меню',
            },
        ),
    ]
