# Generated by Django 4.0.5 on 2022-06-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Текст ссылки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания ссылки')),
            ],
            options={
                'verbose_name_plural': 'Ссылка',
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
